# Generated by Django 6.0.6 on 2026-07-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="tts_rate",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tts_voice_uri",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
