# Generated by Django 6.0.6 on 2026-09-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('capability', models.CharField(choices=[('reporting', 'Reporting & analytics'), ('users', 'User analytics (PII)'), ('audit', 'Content audit & quality'), ('review', 'Content review'), ('publish', 'Publishing & imports'), ('translate', 'Translation queue'), ('content_edit', 'Content-edit queue'), ('authors', 'Author records'), ('language_admin', 'Language administration')], max_length=20)),
                ('verb', models.CharField(choices=[('view', 'View'), ('suggest', 'Suggest (file a job; apply nothing)'), ('act', 'Act (apply changes)'), ('approve', "Approve (confirm others' work; pull high-privilege levers)")], max_length=10)),
                ('languages', models.CharField(default='*', max_length=200)),
                ('granted_by', models.EmailField(blank=True, max_length=254)),
                ('role_label', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('email', 'capability'), name='uniq_admin_grant')],
            },
        ),
    ]
