# Generated by Django 6.0.6 on 2026-09-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_admingrant_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signup_variant',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
