# Generated by Django 6.0.6 on 2026-09-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_signup_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admingrant',
            name='capability',
            field=models.CharField(choices=[('reporting', 'Reporting & analytics'), ('users', 'User analytics (PII)'), ('audit', 'Content audit & quality'), ('review', 'Content review'), ('publish', 'Publishing & imports'), ('translate', 'Translation queue'), ('content_edit', 'Content-edit queue'), ('authors', 'Author records'), ('language_admin', 'Language administration'), ('email', 'Email campaigns (compose & send)')], max_length=20),
        ),
    ]
