# Generated by Django 6.0.8 on 2026-10-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_admingrant_capability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
