# Generated by Django 6.0.8 on 2026-10-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_userprofile_theme_paper_unset"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="palette",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
