import js from '@eslint/js';
import ts from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import globals from 'globals';

// Lint gate for the SvelteKit app. Type-checking is svelte-check's job (npm run
// check); this catches the things a type-checker doesn't — unused vars, likely
// bugs, and Svelte-specific mistakes (a11y, reactivity). Formatting is NOT
// enforced here (no Prettier yet) — that's a separate, higher-churn decision.
export default ts.config(
	{
		ignores: [
			'build/',
			'.svelte-kit/',
			'dist/',
			'node_modules/',
			'src/lib/paraglide/', // generated by Paraglide
			'src/lib/live-locales.generated.ts', // generated
			'local-plugins/**' // vendored/generated build-plugin code (inlined TypeBox)
		]
	},
	js.configs.recommended,
	...ts.configs.recommended,
	...svelte.configs.recommended,
	{
		languageOptions: {
			globals: { ...globals.browser, ...globals.node }
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: { parser: ts.parser }
		}
	},
	{
		rules: {
			// This app routes through its own `localizeHref()` (URL-prefixed
			// locales) and guards built links with href.test.ts / check-slashes;
			// adopting SvelteKit's resolve() across ~180 links is a separate
			// migration, not lint hygiene.
			'svelte/no-navigation-without-resolve': 'off',
			// Opinionated and false-positive-prone (flags every non-reactive
			// Map/Set/Date). Not worth the churn/risk in this pass.
			'svelte/prefer-svelte-reactivity': 'off',
			// A bare `this.ticks;` / `syncTick;` statement is this codebase's
			// deliberate Svelte 5 idiom for registering a reactive dependency;
			// the rule reads those legitimate reads as dead expressions.
			'@typescript-eslint/no-unused-expressions': 'off',
			// `{' '}` is intentional whitespace control in {#each} templates.
			'svelte/no-useless-mustaches': 'off',
			// Stylistic $state+$effect → writable-$derived refactor; a reactivity
			// change we don't want a lint gate to force in this pass.
			'svelte/prefer-writable-derived': 'off',
			// svelte-check (npm run check) is the authority on whether a
			// `svelte-ignore` is needed; the plugin's own compiler view can
			// disagree, and removing a live a11y ignore would break `check`.
			'svelte/no-unused-svelte-ignore': 'off',
			// Allow intentionally-unused names when prefixed with `_` (event
			// params, destructure rest, throwaway bindings).
			'@typescript-eslint/no-unused-vars': [
				'error',
				{
					argsIgnorePattern: '^_',
					varsIgnorePattern: '^_',
					caughtErrorsIgnorePattern: '^_',
					destructuredArrayIgnorePattern: '^_'
				}
			]
		}
	}
);
