# Generated by Django 6.0.6 on 2026-07-05 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_slug', models.SlugField(max_length=160)),
                ('language', models.CharField(default='en', max_length=10)),
                ('chapter_order', models.PositiveIntegerField()),
                ('highlights', models.JSONField(default=list)),
                ('notes', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['book_slug', 'chapter_order'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'book_slug', 'chapter_order'), name='uniq_marks_profile_book_chapter')],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_slug', models.SlugField(max_length=160)),
                ('language', models.CharField(default='en', max_length=10)),
                ('chapter_order', models.PositiveIntegerField(default=1)),
                ('paragraph_index', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'book_slug'), name='uniq_progress_profile_book')],
            },
        ),
    ]
