# Generated by Django 6.0.6 on 2026-07-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptermarks',
            name='marks',
            field=models.JSONField(default=list),
        ),
    ]
