# Generated by Django 6.0.6 on 2026-07-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_tts_rate_userprofile_tts_voice_uri'),
        ('reading', '0003_convert_legacy_marks'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chaptermarks',
            name='uniq_marks_profile_book_chapter',
        ),
        migrations.RemoveConstraint(
            model_name='readingprogress',
            name='uniq_progress_profile_book',
        ),
        migrations.AddField(
            model_name='chaptermarks',
            name='kind',
            field=models.CharField(choices=[('book', 'Book'), ('sermon', 'Sermon')], default='book', max_length=10),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='kind',
            field=models.CharField(choices=[('book', 'Book'), ('sermon', 'Sermon')], default='book', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='chaptermarks',
            constraint=models.UniqueConstraint(fields=('profile', 'kind', 'book_slug', 'chapter_order'), name='uniq_marks_profile_work_chapter'),
        ),
        migrations.AddConstraint(
            model_name='readingprogress',
            constraint=models.UniqueConstraint(fields=('profile', 'kind', 'book_slug'), name='uniq_progress_profile_work'),
        ),
    ]
