# Generated by Django 6.0.6 on 2026-07-21 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_tts_rate_userprofile_tts_voice_uri"),
        ("reading", "0003_convert_legacy_marks"),
    ]

    operations = [
        migrations.CreateModel(
            name="SermonMarks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sermon_slug", models.SlugField(max_length=160)),
                ("language", models.CharField(default="en", max_length=10)),
                ("marks", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sermon_marks",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["sermon_slug"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "sermon_slug"),
                        name="uniq_sermon_marks_profile_slug",
                    )
                ],
            },
        ),
    ]
