# Generated by Django 6.0.6 on 2026-07-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0006_fold_sermon_marks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chaptermarks",
            name="kind",
            field=models.CharField(
                choices=[("book", "Book"), ("sermon", "Sermon"), ("bio", "Biography")],
                default="book",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="readingprogress",
            name="kind",
            field=models.CharField(
                choices=[("book", "Book"), ("sermon", "Sermon"), ("bio", "Biography")],
                default="book",
                max_length=10,
            ),
        ),
    ]
