# Generated by Django 6.0.6 on 2026-07-22 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_tts_rate_userprofile_tts_voice_uri"),
        ("reading", "0007_alter_chaptermarks_kind_alter_readingprogress_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("author", "Author"),
                            ("book", "Book"),
                            ("plan", "Plan"),
                            ("sermon", "Sermon"),
                        ],
                        max_length=10,
                    ),
                ),
                ("slug", models.SlugField(max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "kind", "slug"),
                        name="uniq_favorite_profile_item",
                    )
                ],
            },
        ),
    ]
