# Generated by Django 6.0.6 on 2026-07-23 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_tts_rate_userprofile_tts_voice_uri"),
        ("reading", "0009_favorite_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_days",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-day"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "day"), name="uniq_readingday_profile_day"
                    )
                ],
            },
        ),
    ]
