# Generated by Django 6.0.6 on 2026-07-24 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_tts_rate_userprofile_tts_voice_uri'),
        ('reading', '0011_readingday_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_slug', models.SlugField(max_length=160)),
                ('started_at', models.DateTimeField()),
                ('done', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_progress', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'plan_slug'), name='uniq_planprogress_profile_plan')],
            },
        ),
    ]
