"""Indexes for the queries that actually run.

Every one of these serves a query whose leading column the existing UNIQUE
constraint does not match, so none of them could be served by what was already
there — `unique(slug, language)` cannot answer "published books in Spanish,
ordered for the shelf", and `unique(profile, kind, book_slug)` cannot answer
"how many readers per work".

Safe to apply online here: these tables are small (hundreds of books and
sermons, ~3,000 chapters, a search log trimmed to 180 days), so a plain
CREATE INDEX takes milliseconds and the brief write lock passes unnoticed
inside the pre-deploy migrate. CONCURRENTLY would be the right call on a table
where it would not — worth remembering if the library grows by an order of
magnitude.
"""

# Generated by Django 6.0.6 on 2026-08-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_revoke_anon_public_schema"),
        ("reading", "0014_rls_remaining_tables"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="readingprogress",
            index=models.Index(fields=["kind", "book_slug"], name="idx_progress_work"),
        ),
        migrations.AddIndex(
            model_name="readingprogress",
            index=models.Index(fields=["updated_at"], name="idx_progress_updated"),
        ),
    ]
