# Generated by Django 6.0.6 on 2026-08-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0015_add_query_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptermarks',
            name='deleted',
            field=models.JSONField(default=dict),
        ),
    ]
