# Generated by Django 6.0.6 on 2026-09-01 16:28

from django.db import migrations, models
from django.db.models import F


def _backfill_client_time(apps, schema_editor):
    """Seed the recency baseline for rows that predate this field.

    Every existing row is NULL after the AddField. Without a baseline the sign-in
    merge can't tell a stale incoming position from a fresh one and would overwrite
    a newer server position during the transition window. Copy `updated_at` (the
    last-save time) in — it is necessarily BEFORE any post-deploy client timestamp,
    so the first live PUT still lands and repopulates it with a real client time.
    `update()` bypasses save(), so `updated_at`'s auto_now does not fire.
    """
    ReadingProgress = apps.get_model("reading", "ReadingProgress")
    ReadingProgress.objects.filter(client_updated_at__isnull=True).update(
        client_updated_at=F("updated_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0016_chaptermarks_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='client_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(_backfill_client_time, migrations.RunPython.noop),
    ]
