# Generated by Django 6.0.6 on 2026-09-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0016_chaptermarks_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='client_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
