# Generated by Django 6.0.6 on 2026-09-02 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_revoke_anon_public_schema'),
        ('reading', '0017_readingprogress_client_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('book', 'Book'), ('sermon', 'Sermon'), ('bio', 'Biography')], default='book', max_length=10)),
                ('book_slug', models.SlugField(max_length=160)),
                ('chapter_order', models.PositiveIntegerField(default=1)),
                ('paragraph_index', models.PositiveIntegerField(default=0)),
                ('bm_id', models.CharField(blank=True, max_length=80)),
                ('snippet', models.CharField(blank=True, max_length=300)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['book_slug', 'chapter_order', 'paragraph_index'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'kind', 'book_slug', 'chapter_order', 'paragraph_index'), name='uniq_bookmark_profile_spot')],
            },
        ),
    ]
