# Generated by Django 6.0.6 on 2026-09-12 18:59
#
# No backfill. `finished_at` starts null for every existing row — deliberately.
# The old "finished" signal was a client-side GUESS (a book whose last-opened
# chapter was its last), never a stored fact, and it only existed for books.
# Seeding it here would stamp that guess into an authoritative field — marking a
# book "finished" for a reader who merely opened its last chapter, and still
# leaving every sermon/bio unfinishable. Starting clean is the honest baseline:
# a reader's real completions accrue from here (auto-detected at the end of a
# read, or marked explicitly), and any book they had actually finished simply
# re-enters "Continue reading" until they finish it once more. See models.py.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0020_favorite_topic_article_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="readingprogress",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
