# Generated by Django 6.0.6 on 2026-09-13 03:43

import django.db.models.deletion
from django.db import migrations, models

# Row-level security on the new sessions table — same mechanism as the other
# per-user reading tables (0009/0014/0019): the Supabase Data API exposes the
# public schema to the anon key, RLS with no policies denies all non-owner
# access, and Django connects as the table owner so it bypasses RLS. Postgres
# only; SQLite dev has no RLS. accounts/tests_rls.py fails the build for any
# public table without it, so this is required, not optional.
TABLE = "reading_readingsession"


def enable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(f"ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY")


def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(f"ALTER TABLE {TABLE} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_userprofile_timezone"),
        ("reading", "0021_readingprogress_finished_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=80)),
                ("started_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("seconds", models.PositiveIntegerField(default=0)),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("book", "Book"),
                            ("sermon", "Sermon"),
                            ("bio", "Biography"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("book_slug", models.SlugField(blank=True, max_length=160)),
                ("language", models.CharField(blank=True, default="", max_length=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
                "indexes": [
                    models.Index(
                        fields=["profile", "-last_seen_at"],
                        name="idx_session_profile_seen",
                    ),
                    models.Index(fields=["started_at"], name="idx_session_started"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "client_id"),
                        name="uniq_session_profile_client",
                    )
                ],
            },
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
