# Generated by Django 6.0.6 on 2026-09-23 04:03

import django.db.models.deletion
from django.db import migrations, models

# Row-level security on the new tombstone table — same mechanism as the other
# per-user reading tables (see 0022): RLS with no policies denies the Supabase
# anon/authenticated roles; Django connects as the owner and bypasses it.
# Postgres only. accounts/tests_rls.py fails the build for a table without it.
TABLE = "reading_removal"


def enable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(f"ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY")


def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(f"ALTER TABLE {TABLE} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_admingrant_capability'),
        ('reading', '0022_reading_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Removal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('progress', 'Reading position'), ('favorite', 'Favorite')], max_length=10)),
                ('kind', models.CharField(max_length=10)),
                ('slug', models.SlugField(max_length=160)),
                ('removed_at', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removals', to='accounts.userprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'domain', 'kind', 'slug'), name='uniq_removal_profile_item')],
            },
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
