# Generated by Django 6.0.6 on 2026-09-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_admingrant_capability'),
        ('reading', '0023_removal'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='removal',
            name='uniq_removal_profile_item',
        ),
        migrations.AddField(
            model_name='removal',
            name='chapter_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='removal',
            name='paragraph_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='removal',
            name='domain',
            field=models.CharField(choices=[('progress', 'Reading position'), ('favorite', 'Favorite'), ('bookmark', 'Bookmark')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='removal',
            constraint=models.UniqueConstraint(fields=('profile', 'domain', 'kind', 'slug', 'chapter_order', 'paragraph_index'), name='uniq_removal_profile_spot'),
        ),
    ]
