# Generated by Django 6.0.6 on 2026-09-23 03:49

import django.db.models.deletion
from django.db import migrations, models


# Row-level security on the journal table — same mechanism as the other
# per-user reading tables (0009/0014/0019/0022): the Supabase Data API exposes
# the public schema to the anon key, RLS with no policies denies all non-owner
# access, and Django connects as the table owner so it bypasses RLS. Postgres
# only; accounts/tests_rls.py fails the build for any public table without it.
TABLE = "reading_journalentry"


def enable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(f"ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY")


def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(f"ALTER TABLE {TABLE} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_admingrant_capability'),
        ('reading', '0023_removal'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('note', 'Note'), ('prayer', 'Prayer')], default='note', max_length=10)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ref', models.CharField(blank=True, max_length=200)),
                ('person', models.CharField(blank=True, max_length=80)),
                ('group', models.CharField(blank=True, choices=[('family', 'Family'), ('friends', 'Friends'), ('church', 'Church'), ('missions', 'Missions'), ('work', 'Work'), ('world', 'The world')], max_length=20)),
                ('remind', models.CharField(blank=True, max_length=20)),
                ('updates', models.JSONField(blank=True, default=list)),
                ('source', models.JSONField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('client_created_at', models.DateTimeField()),
                ('client_updated_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-client_created_at'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'entry_id'), name='uniq_journal_profile_entry')],
            },
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
