# Generated by Django 6.0.6 on 2026-09-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0024_journal_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='kind',
            field=models.CharField(choices=[('note', 'Note'), ('prayer', 'Prayer'), ('daily', 'Daily prayer')], default='note', max_length=10),
        ),
    ]
