# Generated by Django 6.0.6 on 2026-09-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0024_removal_bookmark_spot'),
        ('reading', '0025_journal_daily_kind'),
    ]

    operations = [
    ]
