# Generated by Django 6.0.6 on 2026-09-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0026_merge_removal_and_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='collection',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
