# Generated by Django 6.0.6 on 2026-09-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0027_journal_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
