# Generated by Django 6.0.6 on 2026-09-23 22:59

import django.db.models.deletion
from django.db import migrations, models

# Row-level security on the new table — same as the other per-user reading
# tables (see 0022): RLS with no policies denies the Supabase anon/authenticated
# roles; Django connects as the owner. accounts/tests_rls.py enforces it.
TABLE = "reading_customshelf"


def enable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(f"ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY")


def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(f"ALTER TABLE {TABLE} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_admingrant_capability'),
        ('reading', '0028_journal_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('books', models.JSONField(blank=True, default=list)),
                ('deleted', models.BooleanField(default=False)),
                ('client_created_at', models.DateTimeField()),
                ('client_updated_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['client_created_at'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'shelf_id'), name='uniq_shelf_profile_id')],
            },
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
