# Generated by Django 6.0.6 on 2026-09-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0029_custom_shelf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="kind",
            field=models.CharField(
                choices=[
                    ("book", "Book"),
                    ("sermon", "Sermon"),
                    ("bio", "Biography"),
                    ("article", "Article"),
                ],
                default="book",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="chaptermarks",
            name="kind",
            field=models.CharField(
                choices=[
                    ("book", "Book"),
                    ("sermon", "Sermon"),
                    ("bio", "Biography"),
                    ("article", "Article"),
                ],
                default="book",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="readingprogress",
            name="kind",
            field=models.CharField(
                choices=[
                    ("book", "Book"),
                    ("sermon", "Sermon"),
                    ("bio", "Biography"),
                    ("article", "Article"),
                ],
                default="book",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="readingsession",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("book", "Book"),
                    ("sermon", "Sermon"),
                    ("bio", "Biography"),
                    ("article", "Article"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
