# Generated by Django 6.0.8 on 2026-09-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0030_work_kind_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='furthest_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='pct',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
