# Generated by Django 6.0.8 on 2026-10-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_admingrant_capability'),
        ('reading', '0032_move_series_plan_progress'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='readingprogress',
            index=models.Index(condition=models.Q(('finished_at__isnull', False)), fields=['kind', 'finished_at'], name='idx_progress_finished'),
        ),
    ]
