# Generated by Django 6.0.8 on 2026-10-03 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_admingrant_capability'),
        ('reading', '0033_readingprogress_idx_progress_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_slug', models.SlugField(max_length=160)),
                ('start_on', models.DateField(blank=True, null=True)),
                ('reading_days', models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Weekdays'), ('monsat', 'Monsat')], default='daily', max_length=10)),
                ('remind_at', models.CharField(blank=True, default='', max_length=5)),
                ('client_updated_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_schedules', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'plan_slug'), name='uniq_planschedule_profile_plan')],
            },
        ),
    ]
