# Generated by Django 6.0.8 on 2026-10-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_admingrant_capability"),
        ("reading", "0034_planschedule"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="readingday",
            index=models.Index(fields=["day"], name="idx_readingday_day"),
        ),
    ]
