# Generated by Django 6.0.8 on 2026-10-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0035_readingday_day_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="planschedule",
            name="email_reminder",
            field=models.BooleanField(default=False),
        ),
    ]
