# Generated by Django 6.0.8 on 2026-10-11 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_prompttally"),
        ("reading", "0036_planschedule_email_reminder"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16, unique=True)),
                ("plan_slug", models.SlugField(max_length=160)),
                ("start_on", models.DateField()),
                (
                    "reading_days",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekdays", "Weekdays"),
                            ("monsat", "Monsat"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reading_groups_led",
                        to="accounts.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReadingGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("baseline", models.JSONField(default=list)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="reading.readinggroup",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_groups",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "profile"), name="uniq_readinggroupmember"
                    )
                ],
            },
        ),
    ]
