# Generated by Django 6.0.6 on 2026-09-18 17:59

import django.db.models.deletion
import emails.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_userprofile_signup_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.JSONField(default=dict)),
                ('body_html', models.JSONField(default=dict)),
                ('audience', models.JSONField(blank=True, default=dict)),
                ('from_address', models.CharField(blank=True, max_length=200)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('canceled', 'Canceled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('kind', models.CharField(choices=[('lifecycle', 'Lifecycle'), ('broadcast', 'Broadcast')], max_length=20)),
                ('lifecycle_step', models.CharField(blank=True, max_length=60)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('broadcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='emails.broadcast')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('delivery_delayed', 'Delivery delayed'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('failed', 'Failed')], max_length=30)),
                ('url', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('provider_event_id', models.CharField(blank=True, max_length=200)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='emails.emailmessage')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifecycle_opt_in', models.BooleanField(default=True)),
                ('newsletter_opt_in', models.BooleanField(default=True)),
                ('unsubscribed_all', models.BooleanField(default=False)),
                ('suppressed_at', models.DateTimeField(blank=True, null=True)),
                ('suppression_reason', models.CharField(blank=True, max_length=40)),
                ('unsubscribe_token', models.CharField(default=emails.models._new_token, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_subscription', to='accounts.userprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['kind', 'lifecycle_step'], name='emails_emai_kind_bbdf06_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['recipient', '-created_at'], name='emails_emai_recipie_1a21f9_idx'),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['message', 'type'], name='emails_emai_message_d52939_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailevent',
            constraint=models.UniqueConstraint(fields=('message', 'type', 'provider_event_id'), name='uniq_event_message_type_provider'),
        ),
    ]
