# Generated by Django 6.0.6 on 2026-09-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_rls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcast',
            name='body_html',
        ),
        migrations.AddField(
            model_name='broadcast',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
