# Generated by Django 6.0.8 on 2026-10-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_remove_broadcast_body_html_broadcast_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscription',
            name='email_locale',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='emailsubscription',
            name='stream_prefs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
