# Generated by Django 6.0.8 on 2026-10-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0004_emailsubscription_email_locale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="guardrail_override",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="pause_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="send_cursor",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="send_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="send_lease_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="send_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="send_tally",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="tested_digest",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="body_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="sent_by",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("sending", "Sending"),
                    ("paused", "Paused"),
                    ("sent", "Sent"),
                    ("canceled", "Canceled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("lifecycle", "Lifecycle"),
                    ("broadcast", "Broadcast"),
                    ("direct", "Direct"),
                ],
                max_length=20,
            ),
        ),
    ]
