# Generated by Django 6.0.8 on 2026-10-02 02:04

from django.db import migrations, models


def settle_legacy_rows(apps, schema_editor):
    """Bring rows written by the old in-request sender into the new model.

    * A broadcast left in ``sending`` (the old request timed out or crashed
      mid-send) must not be picked up and resumed automatically by the new
      cron — possibly weeks later. Pause it, saying why; an admin can resume.
    * Test sends were told apart only by their key prefix; flag them so they
      stay out of results and the guardrail.
    """
    Broadcast = apps.get_model("emails", "Broadcast")
    EmailMessage = apps.get_model("emails", "EmailMessage")
    Broadcast.objects.filter(status="sending").update(
        status="paused",
        status_reason="Paused at upgrade: it was mid-send under the old sender. "
        "Resume to send to the rest.",
    )
    EmailMessage.objects.filter(idempotency_key__startswith="broadcast-test:").update(is_test=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_admingrant_capability"),
        ("emails", "0004_emailsubscription_email_locale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="guardrail_override",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="send_cursor",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="send_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="send_lease_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="send_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="send_tally",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="status_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="tested_digest",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="body_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="is_test",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="sent_by",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("sending", "Sending"),
                    ("paused", "Paused"),
                    ("sent", "Sent"),
                    ("canceled", "Canceled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("lifecycle", "Lifecycle"),
                    ("broadcast", "Broadcast"),
                    ("direct", "Direct"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["sent_at"], name="emails_emai_sent_at_9dee2e_idx"
            ),
        ),
        migrations.RunPython(settle_legacy_rows, migrations.RunPython.noop),
    ]
