# Generated by Django 6.0.8 on 2026-10-03 03:42

from django.db import migrations, models


def enable_rls(apps, schema_editor):
    # Every public table has RLS (see emails/0002_rls): no policies = deny-all
    # through Supabase's anon API; Django owns the table and bypasses it.
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("ALTER TABLE emails_emailtemplate ENABLE ROW LEVEL SECURITY")


def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("ALTER TABLE emails_emailtemplate DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0005_batched_send_and_direct_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("subject", models.JSONField(blank=True, default=dict)),
                ("content", models.JSONField(blank=True, default=dict)),
                ("created_by", models.CharField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
