# Generated by Django 6.0.8 on 2026-10-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0006_email_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="translations",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
