"""Deriving a rough country from a reader's IANA timezone.

We capture only the browser's IANA timezone (``UserProfile.timezone``) — never
an IP address — so the geography here is approximate and privacy-light: a
timezone names a region, not a person. The map below is deliberately kept as
*derivation* (not a stored country column) so it can be corrected or extended
without re-capturing anything from readers.

Coverage is the populous zones that real sign-ups actually report; an unlisted
or blank timezone falls through to ``None`` and is bucketed as "Unknown" by the
admin analytics, while the raw timezone breakdown still counts it. This is a
lookup table, not an authority — if precise per-country numbers ever matter,
that is a server-side IP/GeoIP job, and its trade-offs (personal data, consent)
are a separate decision.
"""

from __future__ import annotations

# IANA timezone → ISO 3166-1 alpha-2 country code. One entry per zone; multiple
# zones can map to the same country (the US and Australia especially).
COUNTRY_BY_TZ: dict[str, str] = {
    # North America
    "America/New_York": "US",
    "America/Detroit": "US",
    "America/Chicago": "US",
    "America/Denver": "US",
    "America/Phoenix": "US",
    "America/Los_Angeles": "US",
    "America/Anchorage": "US",
    "America/Adak": "US",
    "Pacific/Honolulu": "US",
    "America/Toronto": "CA",
    "America/Vancouver": "CA",
    "America/Edmonton": "CA",
    "America/Winnipeg": "CA",
    "America/Halifax": "CA",
    "America/St_Johns": "CA",
    "America/Mexico_City": "MX",
    "America/Tijuana": "MX",
    "America/Monterrey": "MX",
    "America/Cancun": "MX",
    # Central America & Caribbean
    "America/Guatemala": "GT",
    "America/El_Salvador": "SV",
    "America/Tegucigalpa": "HN",
    "America/Managua": "NI",
    "America/Costa_Rica": "CR",
    "America/Panama": "PA",
    "America/Havana": "CU",
    "America/Santo_Domingo": "DO",
    "America/Port-au-Prince": "HT",
    "America/Jamaica": "JM",
    "America/Puerto_Rico": "PR",
    "America/Port_of_Spain": "TT",
    # South America
    "America/Bogota": "CO",
    "America/Lima": "PE",
    "America/Caracas": "VE",
    "America/Guayaquil": "EC",
    "America/La_Paz": "BO",
    "America/Asuncion": "PY",
    "America/Santiago": "CL",
    "America/Argentina/Buenos_Aires": "AR",
    "America/Argentina/Cordoba": "AR",
    "America/Montevideo": "UY",
    "America/Sao_Paulo": "BR",
    "America/Bahia": "BR",
    "America/Fortaleza": "BR",
    "America/Manaus": "BR",
    "America/Recife": "BR",
    # Europe
    "Europe/London": "GB",
    "Europe/Dublin": "IE",
    "Europe/Lisbon": "PT",
    "Europe/Madrid": "ES",
    "Europe/Paris": "FR",
    "Europe/Brussels": "BE",
    "Europe/Amsterdam": "NL",
    "Europe/Berlin": "DE",
    "Europe/Zurich": "CH",
    "Europe/Vienna": "AT",
    "Europe/Rome": "IT",
    "Europe/Copenhagen": "DK",
    "Europe/Oslo": "NO",
    "Europe/Stockholm": "SE",
    "Europe/Helsinki": "FI",
    "Europe/Warsaw": "PL",
    "Europe/Prague": "CZ",
    "Europe/Budapest": "HU",
    "Europe/Bratislava": "SK",
    "Europe/Bucharest": "RO",
    "Europe/Sofia": "BG",
    "Europe/Athens": "GR",
    "Europe/Zagreb": "HR",
    "Europe/Belgrade": "RS",
    "Europe/Kyiv": "UA",
    "Europe/Kiev": "UA",
    "Europe/Moscow": "RU",
    "Europe/Istanbul": "TR",
    "Europe/Tallinn": "EE",
    "Europe/Riga": "LV",
    "Europe/Vilnius": "LT",
    # Africa
    "Africa/Casablanca": "MA",
    "Africa/Algiers": "DZ",
    "Africa/Tunis": "TN",
    "Africa/Cairo": "EG",
    "Africa/Lagos": "NG",
    "Africa/Accra": "GH",
    "Africa/Abidjan": "CI",
    "Africa/Dakar": "SN",
    "Africa/Kinshasa": "CD",
    "Africa/Nairobi": "KE",
    "Africa/Kampala": "UG",
    "Africa/Dar_es_Salaam": "TZ",
    "Africa/Addis_Ababa": "ET",
    "Africa/Kigali": "RW",
    "Africa/Lusaka": "ZM",
    "Africa/Harare": "ZW",
    "Africa/Maputo": "MZ",
    "Africa/Johannesburg": "ZA",
    "Africa/Windhoek": "NA",
    # Middle East
    "Asia/Jerusalem": "IL",
    "Asia/Beirut": "LB",
    "Asia/Amman": "JO",
    "Asia/Damascus": "SY",
    "Asia/Baghdad": "IQ",
    "Asia/Riyadh": "SA",
    "Asia/Dubai": "AE",
    "Asia/Qatar": "QA",
    "Asia/Kuwait": "KW",
    "Asia/Tehran": "IR",
    # South & Central Asia
    "Asia/Karachi": "PK",
    "Asia/Kolkata": "IN",
    "Asia/Calcutta": "IN",
    "Asia/Colombo": "LK",
    "Asia/Dhaka": "BD",
    "Asia/Kathmandu": "NP",
    "Asia/Tashkent": "UZ",
    "Asia/Almaty": "KZ",
    # East & Southeast Asia
    "Asia/Bangkok": "TH",
    "Asia/Ho_Chi_Minh": "VN",
    "Asia/Saigon": "VN",
    "Asia/Jakarta": "ID",
    "Asia/Kuala_Lumpur": "MY",
    "Asia/Singapore": "SG",
    "Asia/Manila": "PH",
    "Asia/Hong_Kong": "HK",
    "Asia/Taipei": "TW",
    "Asia/Shanghai": "CN",
    "Asia/Seoul": "KR",
    "Asia/Tokyo": "JP",
    "Asia/Yangon": "MM",
    "Asia/Phnom_Penh": "KH",
    # Oceania
    "Australia/Perth": "AU",
    "Australia/Adelaide": "AU",
    "Australia/Darwin": "AU",
    "Australia/Brisbane": "AU",
    "Australia/Sydney": "AU",
    "Australia/Melbourne": "AU",
    "Australia/Hobart": "AU",
    "Pacific/Auckland": "NZ",
    "Pacific/Fiji": "FJ",
    "Pacific/Port_Moresby": "PG",
    "Pacific/Guam": "GU",
}

# Display names for the codes above (plus the "unknown" sentinel). Only the
# countries COUNTRY_BY_TZ can actually produce need a name here.
COUNTRY_NAMES: dict[str, str] = {
    "AE": "United Arab Emirates",
    "AR": "Argentina",
    "AT": "Austria",
    "AU": "Australia",
    "BD": "Bangladesh",
    "BE": "Belgium",
    "BG": "Bulgaria",
    "BO": "Bolivia",
    "BR": "Brazil",
    "CA": "Canada",
    "CD": "DR Congo",
    "CH": "Switzerland",
    "CI": "Côte d’Ivoire",
    "CL": "Chile",
    "CN": "China",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CZ": "Czechia",
    "DE": "Germany",
    "DK": "Denmark",
    "DO": "Dominican Republic",
    "DZ": "Algeria",
    "EC": "Ecuador",
    "EE": "Estonia",
    "EG": "Egypt",
    "ES": "Spain",
    "ET": "Ethiopia",
    "FI": "Finland",
    "FJ": "Fiji",
    "FR": "France",
    "GB": "United Kingdom",
    "GH": "Ghana",
    "GR": "Greece",
    "GT": "Guatemala",
    "GU": "Guam",
    "HK": "Hong Kong",
    "HN": "Honduras",
    "HR": "Croatia",
    "HT": "Haiti",
    "HU": "Hungary",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IN": "India",
    "IQ": "Iraq",
    "IR": "Iran",
    "IT": "Italy",
    "JM": "Jamaica",
    "JO": "Jordan",
    "JP": "Japan",
    "KE": "Kenya",
    "KH": "Cambodia",
    "KR": "South Korea",
    "KW": "Kuwait",
    "KZ": "Kazakhstan",
    "LB": "Lebanon",
    "LK": "Sri Lanka",
    "LT": "Lithuania",
    "LV": "Latvia",
    "MA": "Morocco",
    "MM": "Myanmar",
    "MX": "Mexico",
    "MY": "Malaysia",
    "MZ": "Mozambique",
    "NA": "Namibia",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "Netherlands",
    "NO": "Norway",
    "NP": "Nepal",
    "NZ": "New Zealand",
    "PA": "Panama",
    "PE": "Peru",
    "PG": "Papua New Guinea",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Poland",
    "PR": "Puerto Rico",
    "PT": "Portugal",
    "PY": "Paraguay",
    "QA": "Qatar",
    "RO": "Romania",
    "RS": "Serbia",
    "RU": "Russia",
    "SA": "Saudi Arabia",
    "SE": "Sweden",
    "SG": "Singapore",
    "SK": "Slovakia",
    "SV": "El Salvador",
    "SY": "Syria",
    "TH": "Thailand",
    "TN": "Tunisia",
    "TR": "Türkiye",
    "TT": "Trinidad & Tobago",
    "TW": "Taiwan",
    "TZ": "Tanzania",
    "UA": "Ukraine",
    "UG": "Uganda",
    "US": "United States",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "ZA": "South Africa",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
}


def country_for_timezone(tz: str) -> str | None:
    """ISO alpha-2 country for an IANA timezone, or ``None`` if unmapped/blank."""
    return COUNTRY_BY_TZ.get(tz.strip()) if tz else None


def country_name(code: str) -> str:
    """Display name for a country code; the code itself if we have no name."""
    return COUNTRY_NAMES.get(code, code)
