// GENERATED by backend/scripts/tune_art_scrim.py — do not edit by hand.
//
// How much scrim each painting needs. The scrim's SHAPE lives in
// `cover-type.css` and in `covers.scrim_alpha`; this is how far it is
// scaled for one picture, measured as the least that still carries white
// type over it. A painting with no entry takes 1, which is the strength
// every painting carried before this table existed.
//
// `coverScrim.test.ts` holds this against `library/art_scrim.py`, and
// `CoverAssetTests` re-measures that against the artwork on disk.

export const COVER_SCRIM: Record<string, number> = {
	'a-call-to-the-unconverted': 0.70,
	'all-of-grace': 0.70,
	'all-things-for-good': 0.85,
	'answers-to-prayer': 0.55,
	'baptism-with-the-holy-spirit': 0.85,
	'clothed-with-strength-and-dignity': 0.30,
	'confessions': 1.00,
	'feasting-at-the-table': 0.80,
	'freedom-of-the-will': 0.95,
	'godliness': 0.30,
	'grace-abounding': 0.65,
	'he-holds-my-tomorrows': 0.55,
	'humility-2': 0.95,
	'jesus-himself-2': 0.65,
	'life-and-diary-of-david-brainerd': 0.70,
	'lord-teach-us-to-pray-2': 0.60,
	'pilgrims-progress': 0.65,
	'prayer-the-pulse-of-life': 0.95,
	'prevailing-prayer': 0.45,
	'purity-of-heart': 0.35,
	'religious-affections': 0.50,
	'revival-lectures': 0.85,
	'selected-sermons-whitefield': 0.60,
	'stepping-stones-2': 0.70,
	'talks-to-the-farmer': 0.50,
	'ten-commandments': 0.90,
	'the-fourfold-gospel': 0.85,
	'the-god-of-all-comfort': 0.95,
	'the-imitation-of-christ': 0.85,
	'the-inner-chamber': 0.30,
	'the-key-in-my-hand': 0.95,
	'the-normal-christian-life': 0.55,
	'the-person-and-work-of-the-holy-spirit': 0.90,
	'the-reformed-pastor': 0.70,
	'the-unselfishness-of-god': 0.95,
	'the-way-to-god': 0.60,
	'till-he-come': 0.75,
	'union-and-communion': 0.85,
	'waiting-on-god': 0.60,
};

/** How far to scale the scrim over one work's painting. */
export function scrimStrength(slug: string): number {
	return COVER_SCRIM[slug] ?? 1;
}
