// GENERATED by scripts/measure-ground-bars.mjs — do not edit by hand.
//
// The flat dark bars along the edges of each painted ground, as the deepest
// bar's fraction of its side. A laid-out cover crops just past them; the framed
// composition's scrim already hides them. `groundBars.test.ts` fails when this
// no longer matches the files: run `npm run covers:bars`.

export const GROUND_BARS: Record<string, number> = {
	'a-hidden-fire': 0.110,
	'answers-to-prayer': 0.105,
	'baptism-with-the-holy-spirit': 0.085,
	'brave-for-god': 0.080,
	'christ-the-healer': 0.030,
	'daughters-of-the-king-1': 0.110,
	'daughters-of-the-king-2': 0.110,
	'daughters-of-the-king-3': 0.110,
	'divine-healing': 0.050,
	'divine-songs-for-children': 0.055,
	'essentials-of-prayer': 0.040,
	'george-muller-of-bristol': 0.110,
	'growing-in-wisdom': 0.110,
	'how-to-bring-men-to-christ': 0.055,
	'hurlbuts-life-of-christ': 0.060,
	'lord-teach-us-to-pray-2': 0.110,
	'men-and-women-who-gave-everything-2': 0.110,
	'necessity-of-prayer': 0.050,
	'power-through-prayer': 0.040,
	'religious-affections': 0.035,
	'revival-lectures': 0.090,
	'rise-up-men-of-god-2': 0.110,
	'school-of-prayer': 0.040,
	'sons-of-the-king-1': 0.110,
	'sons-of-the-king-2': 0.110,
	'sons-of-the-king-3': 0.110,
	'the-reformed-pastor': 0.040,
	'the-unselfishness-of-god': 0.110,
	'till-he-come': 0.040,
	'tukutendereza': 0.110,
	'watchman-nee-a-life': 0.040
};

/** The bar to crop past for a painted ground's url; 0 for anything else. */
export function groundBar(coverUrl: string | null | undefined): number {
	const m = /^\/covers\/art\/([^/]+)\.jpg$/.exec(coverUrl ?? '');
	return (m && GROUND_BARS[m[1]]) || 0;
}
