import { localizeHref as paraglideLocalizeHref } from '$lib/paraglide/runtime';
import { isSlashedPath } from '$lib/canonicalRedirect';

/**
 * Trailing-slash-correct link building.
 *
 * The site is a STATIC bundle (adapter-static), and the detail routes export
 * `trailingSlash = 'always'`, so each prerenders to `<slug>/index.html`. Render
 * serves that file for the slash URL, but the NON-slash URL matches no file and
 * gets the SPA shell — no title, no content and no canonical.
 *
 * So the two forms of a detail URL serve completely different documents:
 *
 *     /books/the-inner-chamber    ->    3,953 b, no <title>   (SPA shell)
 *     /books/the-inner-chamber/   ->   36,877 b, fully rendered
 *
 * Every internal link used to emit the non-slash form, so a crawler following
 * the site's own links only ever saw shells. Routing link construction through
 * here fixes that at the source: links, hreflang alternates and JSON-LD URLs
 * all go through `localizeHref`, so they are corrected in one place and new
 * links get it right by default. The edge 301 in docs/seo-edge-rules.md is the
 * safety net for URLs already in search indexes.
 *
 * Which paths get the slash is `isSlashedPath` — the same rule the canonical
 * redirect uses, kept to "every route that exports `trailingSlash = 'always'`"
 * and pinned to the route tree by `canonicalRedirect.test.ts`. This used to be
 * its own narrower list, which missed `/series/<slug>` and
 * `/biographies/era/<era>`: the book page's series link and the era links sent
 * crawlers to the noindex shell. Index pages (`/books`) resolve via explicit
 * Render rewrites and client-only routes (`/admin`) are not slashed routes, so
 * both are left alone.
 */

/** Append the trailing slash to a slashed-route path, preserving ?query and #hash. */
export function withTrailingSlash(href: string): string {
	// Only app-internal paths; leave external URLs, mailto:, and #anchors alone.
	if (!href.startsWith('/')) return href;

	const [, path, rest] = /^([^?#]*)([?#].*)?$/.exec(href) as RegExpExecArray;
	if (!path || path.endsWith('/')) return href;
	return isSlashedPath(path) ? `${path}/${rest ?? ''}` : href;
}

/**
 * Drop-in replacement for Paraglide's `localizeHref`, applying the trailing
 * slash after localization (the locale prefix is added by Paraglide, so the
 * shape can only be judged once it has run).
 *
 * Import this instead of the Paraglide runtime for anything that renders a URL.
 * Paraglide's runtime is generated — regenerated by `npm run paraglide` on every
 * build — so it cannot be patched directly.
 */
export function localizeHref(
	href: string,
	options?: Parameters<typeof paraglideLocalizeHref>[1]
): string {
	// A fragment ("#plans") is a place on THIS page: no locale, no slash — and
	// Paraglide would otherwise resolve it against the current path.
	if (href.startsWith('#')) return href;
	return withTrailingSlash(paraglideLocalizeHref(href, options));
}
