// GENERATED by scripts/fetch-live-locales.mjs — do not edit by hand.
//
// The locales the Language registry says are LIVE. Regenerated before every
// build from the API, so an admin pressing "Go live" reaches the static site on
// the next deploy. Committed so type-checking and tests work before a build.
export const LIVE_LOCALES = ["en","es","sw","lg","pt"] as const;
