# Generated by Django 6.0.6 on 2026-09-21 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_alter_admingrant_capability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter_email', models.EmailField(blank=True, max_length=254)),
                ('submitter_role', models.CharField(blank=True, max_length=40)),
                ('category', models.CharField(choices=[('language', 'Language / translation'), ('content', 'Content'), ('feature', 'Feature idea'), ('bug', 'Bug'), ('other', 'Other')], default='other', max_length=20)),
                ('body', models.TextField()),
                ('page_url', models.TextField(blank=True)),
                ('content_kind', models.CharField(blank=True, max_length=20)),
                ('content_slug', models.CharField(blank=True, max_length=200)),
                ('content_language', models.CharField(blank=True, db_index=True, max_length=20)),
                ('chapter_ref', models.CharField(blank=True, max_length=100)),
                ('ui_locale', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaging', 'Triaging'), ('planned', 'Planned'), ('in_progress', 'In progress'), ('done', 'Done'), ('declined', 'Declined'), ('duplicate', 'Duplicate')], default='new', max_length=20)),
                ('assignee_email', models.EmailField(blank=True, max_length=254)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='feedback.feedback')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='feedback_fe_status_212662_idx'), models.Index(fields=['category', '-created_at'], name='feedback_fe_categor_3f7830_idx')],
            },
        ),
    ]
