# Generated by Django 6.0.6 on 2026-09-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='source',
            field=models.CharField(choices=[('menu', 'Account menu'), ('fab', 'Floating button'), ('highlight', 'Highlighted text')], default='menu', max_length=20),
        ),
    ]
