# Generated by Django 6.0.6 on 2026-09-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='anchor_block',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='selected_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='suggested_text',
            field=models.TextField(blank=True),
        ),
    ]
